routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();


Route::resource('trucks', App\Http\Controllers\TruckController::class);

Route::resource('userDetails', App\Http\Controllers\UserDetailController::class);

Route::resource('drivers', App\Http\Controllers\DriverController::class);

app/Models/UserDetail.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class UserDetail
 * @package App\Models
 * @version July 17, 2021, 1:05 pm UTC
 *
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $gender
 * @property integer $phone_no
 * @property string $status
 */
class UserDetail extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'user_details';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'email',
        'password',
        'gender',
        'type',
        'phone_no',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string',
        'email' => 'string',
        'password' => 'string',
        'gender' => 'string',
        'type' => 'string',
        'phone_no' => 'integer',
        'status' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        // 'name' => 'required',
        // 'email' => 'required',
        // 'password' => 'required',
        // 'gender' => 'required',
        // 'phone_no' => 'required'
    ];

    
}

app/Http/Controllers/UserDetailController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UserDetailDataTable;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Requests\CreateUserDetailRequest;
use App\Http\Requests\UpdateUserDetailRequest;
use App\Repositories\UserDetailRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;
use Datatables;

class UserDetailController extends AppBaseController
{
    /** @var  UserDetailRepository */
    private $userDetailRepository;

    public function __construct(UserDetailRepository $userDetailRepo)
    {
        $this->userDetailRepository = $userDetailRepo;
    }

    /**
     * Display a listing of the UserDetail.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return Datatables::of((new UserDetailDataTable())->get())->make(true);
        }
    
        return view('user_details.index');
    }

    /**
     * Show the form for creating a new UserDetail.
     *
     * @return Response
     */
    public function create()
    {
        return view('user_details.create');
    }

    /**
     * Store a newly created UserDetail in storage.
     *
     * @param CreateUserDetailRequest $request
     *
     * @return Response
     */
    public function store(CreateUserDetailRequest $request)
    {
        $input = $request->all();

        $userDetail = $this->userDetailRepository->create($input);

        Flash::success('User Detail saved successfully.');

        return redirect(route('userDetails.index'));
    }

    /**
     * Display the specified UserDetail.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $userDetail = $this->userDetailRepository->find($id);

        if (empty($userDetail)) {
            Flash::error('User Detail not found');

            return redirect(route('userDetails.index'));
        }

        return view('user_details.show')->with('userDetail', $userDetail);
    }

    /**
     * Show the form for editing the specified UserDetail.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $userDetail = $this->userDetailRepository->find($id);

        if (empty($userDetail)) {
            Flash::error('User Detail not found');

            return redirect(route('userDetails.index'));
        }

        return view('user_details.edit')->with('userDetail', $userDetail);
    }

    /**
     * Update the specified UserDetail in storage.
     *
     * @param  int              $id
     * @param UpdateUserDetailRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUserDetailRequest $request)
    {
        $userDetail = $this->userDetailRepository->find($id);

        if (empty($userDetail)) {
            Flash::error('User Detail not found');

            return redirect(route('userDetails.index'));
        }

        $userDetail = $this->userDetailRepository->update($request->all(), $id);

        Flash::success('User Detail updated successfully.');

        return redirect(route('userDetails.index'));
    }

    /**
     * Remove the specified UserDetail from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $userDetail = $this->userDetailRepository->find($id);

        $userDetail->delete();

        return $this->sendSuccess('User Detail deleted successfully.');
    }
}

resources/views/user_details/create.blade.php
@extends('layouts.app')
@section('title')
    Create User Detail 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">New User Detail</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('userDetails.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'userDetails.store']) !!}
                                    <div class="row">
                                        @include('user_details.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/user_details/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit User Detail 
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">Edit User Detail</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('userDetails.index') }}"  class="btn btn-primary">Back</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($userDetail, ['route' => ['userDetails.update', $userDetail->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('user_details.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/user_details/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Password Field -->
<div class="form-group col-sm-6">
    {!! Form::label('password', 'Password:') !!}
    {!! Form::text('password', null, ['class' => 'form-control']) !!}
</div>

<!-- Gender Field -->
<div class="form-group col-sm-6">
    {!! Form::label('gender', 'Gender:') !!}
    {!! Form::text('gender', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone No Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone_no', 'Phone No:') !!}
    {!! Form::text('phone_no', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('userDetails.index') }}" class="btn btn-light">Cancel</a>
</div>

resources/views/user_details/index.blade.php
@extends('layouts.app')
@section('title')
    User Details 
@endsection
@section('css')
    <link href="{{ asset('assets/css/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css"/>
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>All Users</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('userDetails.create')}}" class="btn btn-primary form-btn">Add User <i class="fas fa-plus"></i></a>
            </div>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    @include('user_details.table')
                    @include('user_details.templates.templates')
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script>
        let recordsURL = "{{ route('userDetails.index') }}/";
    </script>
    <script src="{{ 'http://13.234.136.76/logistics/public/assets/js/jquery.dataTables.min.js' }}"></script>
    <script src="{{ 'http://13.234.136.76/logistics/public/assets/js/custom/custom-datatable.js' }}"></script>
    <script src="{{ 'http://13.234.136.76/logistics/public/assets/js/user_details/user_details.js' }}"></script>
@endsection

resources/views/user_details/show.blade.php
@extends('layouts.app')
@section('title')
    User Detail Details 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>User Detail Details</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('userDetails.index') }}"
                 class="btn btn-primary form-btn float-right">Back</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('user_details.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/user_details/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $userDetail->name }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $userDetail->email }}</p>
</div>

<!-- Password Field -->
<!-- <div class="form-group">
    {!! Form::label('password', 'Password:') !!}
    <p>{{ $userDetail->password }}</p>
</div> -->

<!-- Gender Field -->
<div class="form-group">
    {!! Form::label('gender', 'Gender:') !!}
    <p>{{ $userDetail->gender }}</p>
</div>

<!-- Phone No Field -->
<div class="form-group">
    {!! Form::label('phone_no', 'Phone No:') !!}
    <p>{{ $userDetail->phone_no }}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{{ $userDetail->status }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $userDetail->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $userDetail->updated_at }}</p>
</div>

resources/views/user_details/table.blade.php
<table class="table table-responsive-sm table-striped table-bordered" id="userDetailsTable">
    <thead>
    <tr>
        <th scope="col">name</th>
        <th scope="col">email</th>
        <th scope="col">password</th>
        <th scope="col">gender</th>
        <th scope="col">phone_no</th>
        <th scope="col">status</th>
        <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>